### ISSUE TITLE
Compiler output and configuration issue

### ISSUE THREAD

**Issue by gsscoder** [lfe-rebar3/compile#33]
Some year ago I created an **LFE** project to learning the language, here the [GitHub link](https://github.com/gsscoder/yfinance-lfe).

Original **rebar.config** didn't worked in its original state, so I've re-configured dependencies. Reading documentation I understood the need of having this **rebar3 plugin** properly configured. So I've added instructions presented here to the file.

Please be patient... But too much time is passed, I lost confidence with environment and I can't see the artifact of compilation. I would expect it on `_build/default`.

This how I modified my original **rebar.config**:
```
{erl_opts, [debug_info, {src_dirs, ["test"]}]}.
{lfe_first_files, []}.
{deps_dir, ["deps"]}.
{eunit_compile_opts, [
   {src_dirs, ["test"]}
  ]}.
{deps, [
   {lfe, {git, "https://github.com/rvirding/lfe.git", {"tag", "v1.3"}}},
   {ljson, {git, "https://github.com/lfex/ljson.git", "master"}},
   {ltest, {git, "https://github.com/lfex/ltest.git", {tag, "0.9.0"}}}
  ]}.
{plugins, [
   {'lfe-compile',
    {git, "git://github.com/lfe-rebar3/compile.git",
      {tag, "0.7.0"}}}
  ]}.
{provider_hooks, [
   {post, [{compile, {lfe, compile}}]}
  ]}.
```
This the output of `rebar3 compile` (or `rebar3 lfe compile`, the same):
```
===> Verifying dependencies...
===> Compiling ltest
 ~~>    Finding .lfe files ...
 ~~>    Compiling ./_build/default/plugins/ltest/src/ltest-runner.lfe ...
===> Plugin {'lfe-test',{git,"https://github.com/lfe-rebar3/test.git",
                                    {branch,"master"}}} not available. It will not be used.
===> Compiling lfe-clean
 ~~>    Finding .lfe files ...
 ~~>    Compiling ./_build/default/plugins/lfe-clean/src/lr3-cln-util.lfe ...
===> Plugin {'lfe-clean',{git,"https://github.com/lfe-rebar3/clean.git",
                                     {branch,"master"}}} not available. It will not be used.
```
If I need to post more info, please let me known.

Any help really appreciated! Thanks in advance.

**Comment by oubiwann** [comment]
I suspect this is due to the rather convoluted state of dependencies, etc., in the various LFE libraries. 

Part of that problem will be addressed by the approach taken in the new LFE plugin here: https://github.com/lfe-rebar3/rebar3_lfe where all the LFE-related rebar3 functionality will be in one plugin. Give me a little more time to:
* address some of the open tickets for that project
* update the various LFE libraries to use the new plugin

Then go ahead and open a ticket in the rebar3_lfe project, using that plugin and sharing the problems you are encountering with it.

I'm going to close this ticket since I'm archiving this repo ...
