### ISSUE TITLE
"Unable to run pre hooks for 'compile', command 'compile' in namespace 'lfe' not found."

### ISSUE THREAD

**Issue by hdurer** [lfe-rebar3/compile#7]
I am a newbie at Erlang, but am trying to set up a proper release with apps, which are lfe.

I think this is the simplest setup, it doesn't even have an lfe file, but I still get an error:

I use rebar3 to set up a release and an app:

``` sh
$ rebar3 new release testrel
===> Writing testrel/apps/testrel/src/testrel_app.erl
===> Writing testrel/apps/testrel/src/testrel_sup.erl
===> Writing testrel/apps/testrel/src/testrel.app.src
===> Writing testrel/rebar.config
===> Writing testrel/config/sys.config
===> Writing testrel/config/vm.args
===> Writing testrel/.gitignore
===> Writing testrel/LICENSE
===> Writing testrel/README.md
$ cd testrel/apps
$ rm -rf testrel
$ rebar3 new app testapp
===> Writing testapp/src/testapp_app.erl
===> Writing testapp/src/testapp_sup.erl
===> Writing testapp/src/testapp.app.src
===> Writing testapp/rebar.config
===> Writing testapp/.gitignore
===> Writing testapp/LICENSE
===> Writing testapp/README.md
$ cd testapp
$ cat > rebar.config <<EOF
> {erl_opts, [debug_info]}.
> 
> {deps, [
>         {lfe, {git, "https://github.com/rvirding/lfe.git", {tag, "v0.10.1"}}}
>        ]}.
> 
> {plugins, [
>            {'lfe-compile', {git, "https://github.com/lfe-rebar3/compile.git", {tag, "0.2.1"}}}
>           ]}.
> 
> {provider_hooks, [
>    {pre, [{compile, {lfe, compile}}]}
>   ]}.
> 
> EOF
$ cd ../..
```

But now if I try to compile this release with skeleton app it doesn't work:

``` sh
$ rebar3 compile
rebar3 compile
===> Verifying dependencies...
===> Fetching lfe ({git,"https://github.com/rvirding/lfe.git",{tag,"v0.10.1"}})
===> Compiling lfe
/home/dir/projects/testrel/_build/default/lib/lfe/src/lfe_eval.erl:128: Warning: variable 'M' shadowed in 'fun'
  ...
/home/dir/projects/testrel/_build/default/lib/lfe/src/lfe_ms.erl:302: Warning: function fetch_binding/2 is unused

===> Compiling testapp
===> Unable to run pre hooks for 'compile', command 'compile' in namespace 'lfe' not found.
```

(this exits with an error)
Note that it compile lfe once, and doesn't compile lfe-compile.

But note that it _does_ work in the app:

``` sh
cd apps/testapp/
$ rebar3 compile
rebar3 compile
===> Fetching lfe-compile ({git,"https://github.com/lfe-rebar3/compile.git",
                                {tag,"0.2.1"}})
===> Fetching lfe ({git,"https://github.com/rvirding/lfe.git",{tag,"v0.10.1"}})
===> Compiling lfe
/home/dir/projects/testrel/apps/testapp/_build/default/plugins/lfe/src/lfe_eval.erl:128: Warning: variable 'M' shadowed in 'fun'
 ...
/home/dir/projects/testrel/apps/testapp/_build/default/plugins/lfe/src/lfe_ms.erl:302: Warning: function fetch_binding/2 is unused

===> Compiling lfe-compile
===> Verifying dependencies...
===> Fetching lfe ({git,"https://github.com/rvirding/lfe.git",{tag,"v0.10.1"}})
===> Compiling lfe
/home/dir/projects/testrel/apps/testapp/_build/default/lib/lfe/src/lfe_eval.erl:128: Warning: variable 'M' shadowed in 'fun'
  ...
/home/dir/projects/testrel/apps/testapp/_build/default/lib/lfe/src/lfe_ms.erl:302: Warning: function fetch_binding/2 is unused

===> Compiling testapp
 ~~>    Finding .lfe files ...
```

(no error)
Note that this compiles lfe twice and _does_ compile lfe-compile.

Am I doing something wrong?  How is this meant to work?

**Comment by oubiwann** [comment]
I have personally never used apps (in either Erlang or LFE) so I'm not going to be _too_ much help here. Perhaps @yurrriq or @arpunk can help, since they've used apps before.

Perhaps more importantly: once you _do_ figure this out, this would be _incredibly_ useful information for the LFE community. If you don't mind writing, I'd love to publish a post on the LFE blog written by you with a tutorial on how to do this. If that's not your thing, I'd love to see your notes once you've finished and maybe "ghost write" an LFE blog post for you, based on your notes. Barring that, if you felt like emailing the LFE mail list with your learnings and any gotchas, this would also be great.

Back to the matter at hand ... I can help with one tidbit of information:
- In the second case you show (in `apps/testapp`) lfe is compiling twice due to the fact that it's needed in the regular deps (`_build/default/lib`) as well as the deps for the rebar3 plugins (`_build/default/plugins`).

As far as the more important issue here of the test app not compiling ... maybe I can make a few suggestions:
1. Have you tried with the latest release of the lfe-compile rebar3 plugin, 0.2.2? That has some fixes in it from @yurrriq that _might_ help ...
2. I tried the steps you show above with the default, `rebar3`-generated `rebar.config` and it works as expected. I updated the default `rebar.config` with your settings and it compiled without issue. (It also worked with 0.2.2 of lfe-compile). I tested this with Erlang 17.2 and 18.2 successfully.

So I'm at a bit of a loss, since I can't duplicate your error ... It's a bit late, so let me paste the exact commands I used, just in case I skipped something that you did:

``` bash
cd /tmp
rebar3 new release testrel
cd testrel/apps
rm -rf testrel
rebar3 new app testapp
cat > rebar.config <<EOF
{erl_opts, [debug_info]}.
{deps, [
  {lfe, {git, "https://github.com/rvirding/lfe.git", {tag, "v0.10.1"}}}
  ]}.
{plugins, [
  {'lfe-compile', {git, "https://github.com/lfe-rebar3/compile.git", {tag, "0.2.1"}}}
  ]}.
{provider_hooks, [
  {pre, [{compile, {lfe, compile}}]}
  ]}.
EOF
rebar3 compile
```

**Comment by yurrriq** [comment]
I second everything @oubiwann said and though I haven't tried it myself, everything looks good to me.

The latest `lfe-compile` release with my changes shouldn't make a difference here. The only real change is that it lazily recompiles modules, i.e. only recompile when the source `.lfe` was last modified after the corresponding `.beam`'s last modification.

By default, rebar3 looks in `./apps/*` and `./lib/*` for OTP apps, so this example should work fine. I suspect some other foul play...

**Comment by yurrriq** [comment]
@hdurer, can you copy the output when you run `rebar3 version`?

Mine is:

```
rebar 3.0.0-beta.4+build.3347.ref0f3e716 on Erlang/OTP 18 Erts 7.2.1
```

also:

```
$ cat /usr/local/lib/erlang/releases/*/OTP_*
18.2.4
```

Also note that in order for your release to build, you'll need to:

```
$ cd /home/dir/projects/testrel
$ sed -i 's/testrel/testapp/' rebar.config
```

**Edit**: This example compiles fine for me, too. And the after the `sed` substitution, I can do:

```
$ cd /home/dir/projects/testrel
$ rebar3 release
===> Verifying dependencies...
===> Compiling testapp
 ~~>    Finding .lfe files ...
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/dir/testrel/_build/default/lib
          /home/dir/testrel/apps
          /usr/local/lib/erlang/lib
===> Resolved testapp-0.1.0
===> Dev mode enabled, release will be symlinked
===> release successfully created!
```

**Comment by hdurer** [comment]
Argh!  It turns out it was an outdated(-ish) rebar3 version.

I had:
  `rebar 3.0.0-beta.3+build.3089.ref97ae8d6 on Erlang/OTP 18 Erts 7.2.1`
which didn't work and after an update I now have 
  `rebar 3.0.0-beta.4+build.3349.ref3a27eb6 on Erlang/OTP 18 Erts 7.2.1` 
which does work like a charm.

Thanks all for trying this out and letting me know that I am not doing anything wrong.

i'll close this bug then.

**Comment by yurrriq** [comment]
:tada: I'm glad everything's working now.
