### ISSUE TITLE
Add lfe-rebar3 to hex.pm?

### ISSUE THREAD

**Issue by jaseemabid** [lfe-rebar3/compile#8]
I could write a patch if required. Improves visibility of the plugin.

**Comment by oubiwann** [comment]
Hrm. I'd be interested in seeing that patch, but only if it was a Makefile target (or set of targets). There should be no burden on the users who don't want to use mix, hex, etc., but I don't mind installing extra tools as a maintainer :-)

**Comment by yurrriq** [comment]
@jaseemabid: I've published the [`rebar_lfe_compile` package](https://hex.pm/packages/rebar3_lfe_compile).

@oubiwann: It turns out `rebar3` uses Hex for dependency resolution anyway, so the only time you need to install another tool (namely the `rebar3_hex` plugin) is when you want to `rebar3 hex {publish,search,*}`.

**Update**: There's also nothing stopping users from continuing to use this as `git` a dependency (though I highly recommend against it).

**Comment by yurrriq** [comment]
Rethink this.

**Comment by yurrriq** [comment]
[Should be good now](https://hex.pm/packages/rebar3_lfe_compile).
